name: Deploy - build and create deploy branch  

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install_dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: build
        run: yarn build

      - name: create_deploy_branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist